In [1]:
import numpy as np

In [3]:
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [5]:
print(n1)

[10 20 30 40]


In [7]:
print(n1[2])

30


In [9]:
type(n1)

numpy.ndarray

In [11]:
n2=np.array([[10,30,50],[20,40,60]])
n2
    

array([[10, 30, 50],
       [20, 40, 60]])

In [13]:
print(n2)

[[10 30 50]
 [20 40 60]]


In [15]:
type(n2)

numpy.ndarray

In [17]:
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

In [19]:
type(n3)

numpy.ndarray

In [21]:
n4 = np.zeros((3,3))
n4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
n5 = np.full((2,2),14)
n5

array([[14, 14],
       [14, 14]])

In [25]:

n6 = np.arange(1,10)
n6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
n7 = np.arange(5,50,5)
n7

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
n8 = np.random.randint(1,100,6)
n8

array([13, 46, 94, 16, 75, 27])

In [31]:
n9 = np.array([[1,2,3],[4,5,6]])
n9.shape

(2, 3)

In [33]:
n9.shape = (3,2)
n9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
n11 = np.array([1,2,3])
n12 = np.array([4,5,6])
n11

array([1, 2, 3])

In [37]:
n12

array([4, 5, 6])

In [39]:
np.vstack((n11,n12))

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.hstack((n11,n12))

array([1, 2, 3, 4, 5, 6])

In [43]:
np.column_stack((n11,n12))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
n13 = np.array([10,20,30,40])
n13

array([10, 20, 30, 40])

In [47]:
n14 = np.array([40,20,50,60])
n14

array([40, 20, 50, 60])

In [49]:
np.intersect1d(n13,n14)

array([20, 40])

In [51]:
np.setdiff1d(n13,n14)

array([10, 30])

In [53]:
np.setdiff1d(n14,n13)

array([50, 60])

In [55]:
np.sum([n13,n14])

270

In [57]:
np.sum([n13,n14],axis=0)

array([ 50,  40,  80, 100])

In [59]:
np.sum([n13,n14],axis=1)

array([100, 170])

In [61]:
np.mean([n13])

25.0

In [63]:
np.median([n13])

25.0

In [65]:
np.std([n13])

11.180339887498949